### ISSUE TITLE
Hadith of the Day (HotD)

### ISSUE THREAD

**Issue by moiz-qureshi** [DilwoarH/Mosque-Screen#11]
It would be pretty cool to have an hadith of the day scrolling horizontally on the bottom of the signage. 

Users can add hadiths to a sheet called HOTD on https://docs.google.com/spreadsheets/d/1yVlGjnEhKLi5DSOuJMm7-ec5-iFvuiR7WkbzMdbFP9s/edit?usp=sharing and the HOTD can be randomized from that sheet.

**Comment by DilwoarH** [comment]
@moiz-qureshi - we now have a hadith view, does this solve your issue?

**Comment by masjidalrahman** [comment]
yes, looks beautiful! jzk! :)

**Comment by moiz-qureshi** [comment]
Jzk @DilwoarH , you rock! Looks awesome!

**Comment by moiz-qureshi** [comment]
My one feedback: I preferred displaying the hadeeth as scrolling text at the bottom of the default views 1-4 so its not taking a whole TV view for too long. but this is an amazing start!
